services:
  - type: web
    name: gold-scraper
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python gold_scraper_render.py"
    preBuildCommand: "playwright install chromium"
